language:
- ruby
install:
- bundle install
cache:
- bundler
script:
- LOG_LEVEL=error APP_ENV=test bundle exec rspec -f d
deploy:
- provider: lambda
  function_name: ItemCheckoutFeedUpdater-qa
  description: Listens on the Item kinesis stream to identify checkouts, which it
    writes to an atom feed.
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.5
  module_name: application
  handler_name: handle_event
  timeout: 10
  environment_variables:
   - PLATFORM_API_BASE_URL=https://qa-platform.nypl.org/api/v0.1/
   - NYPL_OAUTH_URL=https://isso.nypl.org/
   - NYPL_OAUTH_ID=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGowaAYJKoZIhvcNAQcGoFswWQIBADBUBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJgrQmkr7pQa4WSF1gIBEIAnLgWjuqFllMpCQWGT/eC/7n/pxFN87zaoJF19zCRHH/ulh4BICTZf
   - NYPL_OAUTH_SECRET=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAx8ZuLftGsgDmOxxBICARCAQ3ZSNw6hWlqI73kLJcs8Zg3O13PKiATfXXDUvGFim/KolFmQDCsVp7JFF9Jg01U++KNtcGJiVev7z3OAPNXc3fqGp6k=
   - MAX_CHECKOUTS_IN_MEMORY=100
   - S3_BUCKET_NAME=item-checkout-feed-qa
   - S3_FEED_KEY=feed.xml
   - LOG_LEVEL=info
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  on:
    branch: qa
notifications:
  email:
    on_failure: always
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - secure: 2mcKNX/wuONTX07uJ+GMmwrAoi2ndpgDgT/IJ31fE6mNrrUVVbhHTyiS07aFnE7zCpbp1KeEb2CBcMmeh6bgyY+/hqDcnYrrgon56yzlCLr60BEaSsO9gWx4uPmDvhNRPcPmcjNv/74Yg29ZitnPAqsIS76V9sqIbMz+7PDDqde7mOvODeIRb818lET7egnHiwzONPoTGbGrfGutHqNS5XV/XDZn/lgWRysJeERfbrAChGD40tzb29njRPyKIchHc9QQSQb9xKdYwO+WwV+4EHb5vXuwsVPwvyyubuSUqStBzEJQuTX7PxNJjrqNv+z7KkjbEs+IxZhD3gD4tOgFIBZNthlAfBCnpg0xXD46Q2KIhWO+1dSrmy8U2D9Uhq5DcoxqfxXEsDLBoZb9dzrvqe/Eo8WEbzHSeRydKxO/hDxz+r4IdjzYUK9xqla90MWwwlzD0kEOn1i2fS9fWT5DiDIQ0ChvrUtZD7xO+j0iPdOt39oIqv4grCiSC0xgncvNwOM8YS/VhGuCnx54rM6aLlq8rYNWnmMgLQYT99fkmFHQX+ZaBcZ3BOtqb00DS/tseBe0K6IiDT9LDYfRZyymULkzT/MM0JLsJYnW97zf6kxifDdBzKzHYBsRFY+/3dC788XMP0c4PohjTWCaGKQJny5mqMZunqW256/gTil9vnU=
  - secure: tKydmUp+bLMDMLWZEdAwkrAVzrKEqZzYeTTQ2KcpirOfOVLYBNl50Tsx7/w5JPluahb1y1wfQxb1dSltv3RUjnXlYYemrYtJB3kzfoSpOvbCg2OTRefNmyuFDJfDxoJ0jNhDRLsOEPJ/RWEc1EPYozI/jMa53UV1ZuniU1WzPFBLaPiz6AIP0GWDPL7EMD/3KUqkF3JcPBVdHgDoto0nArJw+Z4Ndv8d0bGeKTbVYGQVjqpWZWc4/g3qRQIQZ2GHvCdk8/SA7YVy0Q4ykLOXEKfmCesJToxUFAvpm057QtD6gW7m0OXMhQkewgUkgweR1PjTaBtKmR/BM8uhm9dgufb1u629g3UyKKxYxrnSOZ8cHacqhxdQa6p0Fncb6KWJRuD+XvgqC7vnT5lsMnCWM5Fq7Mq308lmkC4t6161txQ1rnCvvGIJyrRtHlaaWXHSQmDK+ry4fPoF9eds6BIVtu/LVod+QtlC0zAK3awL8z5IQJvXbieF9i0OxM3k3TVjDdS88lDz7jpe1Z4knvBjTrmqTUBPnNadTXow0lTbQq2yEIEhvATL6eB9GETOX4kgqOrIJn25Fsk0x+8VPn7ZKfKYF3g03YNKNct7Vy2m3vwb6Yrp5rtZAcTk0lhjigqprbxw3YuyMoJkV5pwOsE+rn2U6Kl7xRKgcIpJDyXkpyA=
  - secure: NSzlGSonBBhk0jHkJ10vwem7/g0IRaB1ibsesTQ4pQoWln6t/67234K8uzeHw6O/peS8YU6AcG3GYjmZwNVOV5Rx4767dsMfYBwlxLDBIag6m8iDjc+YqfAOU4GizSs517in4GzPF3wjOEiBwzQkghK2Xw9a0m1+tG2xu8YTLSobejsXVeSkczMUEPKq8+JW8KP0bI9xp9XJT0PKoiKoTucJpcyF4cjbK8XlFmGAkpVugLp1S5YE+5kpw1HJShMC/gVkUB96VgOKXXESj5X8AogvHwwyqYxKgLNG7pqadDL38YnxXILo8jgb/xnVAtAUed1iLVVd1InokgGwaT8GsdkQxbb2JU80Jsc8YLYsD23plhl9+u+sB8wCwdCgLRCzf/hJ6/Vn6CO0V7Ld8bBI1uLsSQV0a0BFiBdao/vr6byUw3yzz6VWVYxE/1mg5qPE+uE/qECkuPNiuIOuIVqqjI/97CWW9sHaaSHYkIYLHjXrhUGkBUG0hLb5BixjTO8X27l8uFh8xPp81cm51k1OAZ5bwhBv9CnI0p3Kglav89A8YlKH1ou7tw3UEzfoJRmadIGhyrVuXVMBVXPYmFQgPSAKm29tF/QaucMptI8kWiq+LgRj6boTOrAnORnfcntcGHrQ/nmf+WIi0CVJkN6mc2FTOvdE0IZpSmDZQKdFJyg=
