AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sync-item-metadata-to-scsb-listener'

Resources:
  SyncItemMetadataToScsbService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: application.handle_event
      Runtime: ruby2.5
      Timeout: 30
      Environment:
        Variables:
          PLATFORM_API_BASE_URL: 'https://qa-platform.nypl.org/api/v0.1/'
          NYPL_OAUTH_URL: https://isso.nypl.org/
          NYPL_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHgwdgYJKoZIhvcNAQcGoGkwZwIBADBiBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKNYR7Scq3DoD98X1gIBEIA1Gv6KaFWVnQJ28twTH0xiL/9rjUwYh52kqjjLMGxco7eoUTw2hnpU3QIYsxrziLQtxxDJVRI=
          NYPL_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwbUQIGDi3r/uU3ru0CARCAQ2XhqZ/dW0v2s5jhNfNaZpC6x3B+Femv6+v0F3wLHuyYFo5EblXZ0A+Ynf8YZRvjAdX2XXaeZCzVAj1qE1sAr6263/I=
          MAX_CHECKOUTS_IN_MEMORY: 100
          S3_BUCKET_NAME: 'item-checkout-feed-test'
          S3_FEED_KEY: 'feed.xml'
          LOG_LEVEL: debug
          TZ: 'America/New_York'
          RANDOMIZATION_METHOD: 'uniform'
          CHECKOUT_ID_EXPIRE_TIME: 60*60
